# log
logging:  config: classpath:logback-spring.xml
  level:
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: INFO


spring:
  profiles:
    active: node2




